hvd_sentences = [
    "The birch canoe slid on the smooth planks.",
    "Glue the sheet to the dark blue background.",
    "It's easy to tell the depth of a well.",
    "These days a chicken leg is a rare dish.",
    "Rice is often served in round bowls.",
    "The juice of lemons makes fine punch.",
    "The box was thrown beside the parked truck.",
    "The hogs were fed chopped corn and garbage.",
    "Four hours of steady work faced us.",
    "A large size in stockings is hard to sell.",
    "The boy was there when the sun rose.",
    "A rod is used to catch pink salmon.",
    "The source of the huge river is the clear spring.",
    "Kick the ball straight and follow through.",
    "Help the woman get back to her feet.",
    "A pot of tea helps to pass the evening.",
    "Smoky fires lack flame and heat.",
    "The soft cushion broke the man's fall.",
    "The salt breeze came across from the sea.",
    "The girl at the booth sold fifty bonds.",
    "The small pup gnawed a hole in the sock.",
    "The fish twisted and turned on the bent hook.",
    "Press the pants and sew a button on the vest.",
    "The swan dive was far short of perfect.",
    "The beauty of the view stunned the young boy.",
    "Two blue fish swam in the tank.",
    "Her purse was full of useless trash.",
    "The colt reared and threw the tall rider.",
    "It snowed, rained, and hailed the same morning.",
    "Read verse out loud for pleasure.",
    "Hoist the load to your left shoulder.",
    "Take the winding path to reach the lake.",
    "Note closely the size of the gas tank.",
    "Wipe the grease off his dirty face.",
    "Mend the coat before you go out.",
    "The wrist was badly strained and hung limp.",
    "The stray cat gave birth to kittens.",
    "The young girl gave no clear response.",
    "The meal was cooked before the bell rang.",
    "What joy there is in living.",
    "A king ruled the state in the early days.",
    "The ship was torn apart on the sharp reef.",
    "Sickness kept him home the third week.",
    "The wide road shimmered in the hot sun.",
    "The lazy cow lay in the cool grass.",
    "Lift the square stone over the fence.",
    "The rope will bind the seven books at once.",
    "Hop over the fence and plunge in.",
    "The friendly gang left the drug store.",
    "Mesh wire keeps chicks inside.",
    "The frosty air passed through the coat.",
    "The crooked maze failed to fool the mouse.",
    "Adding fast leads to wrong sums.",
    "The show was a flop from the very start.",
    "A saw is a tool used for making boards.",
    "The wagon moved on well oiled wheels.",
    "March the soldiers past the next hill.",
    "A cup of sugar makes sweet fudge.",
    "Place a rosebush near the porch steps.",
    "Both lost their lives in the raging storm.",
    "We talked of the side show in the circus.",
    "Use a pencil to write the first draft.",
    "He ran half way to the hardware store.",
    "The clock struck to mark the third period.",
    "A small creek cut across the field.",
    "Cars and busses stalled in snow drifts.",
    "The set of china hit the floor with a crash.",
    "This is a grand season for hikes on the road.",
    "The dune rose from the edge of the water.",
    "Those words were the cue for the actor to leave.",
    "A yacht slid around the point into the bay.",
    "The two met while playing on the sand.",
    "The ink stain dried on the finished page.",
    "The walled town was seized without a fight.",
    "The lease ran out in sixteen weeks.",
    "A tame squirrel makes a nice pet.",
    "The horn of the car woke the sleeping cop.",
    "The heart beat strongly and with firm strokes.",
    "The pearl was worn in a thin silver ring.",
    "The fruit peel was cut in thick slices.",
    "The Navy attacked the big task force.",
    "See the cat glaring at the scared mouse.",
    "There are more than two factors here.",
    "The hat brim was wide and too droopy.",
    "The lawyer tried to lose his case.",
    "The grass curled around the fence post.",
    "Cut the pie into large parts.",
    "Men strive but seldom get rich.",
    "Always close the barn door tight.",
    "He lay prone and hardly moved a limb.",
    "The slush lay deep along the street.",
    "A wisp of cloud hung in the blue air.",
    "A pound of sugar costs more than eggs.",
    "The fin was sharp and cut the clear water.",
    "The play seems dull and quite stupid.",
    "Bail the boat to stop it from sinking.",
    "The term ended in late june that year.",
    "A Tusk is used to make costly gifts.",
    "Ten pins were set in order.",
    "The bill was paid every third week.",
    "Oak is strong and also gives shade.",
    "Cats and Dogs each hate the other.",
    "The pipe began to rust while new.",
    "Open the crate but don't break the glass.",
    "Add the sum to the product of these three.",
    "Thieves who rob friends deserve jail.",
    "The ripe taste of cheese improves with age.",
    "Act on these orders with great speed.",
    "The hog crawled under the high fence.",
    "Move the vat over the hot fire.",
    "The bark of the pine tree was shiny and dark.",
    "Leaves turn brown and yellow in the fall.",
    "The pennant waved when the wind blew.",
    "Split the log with a quick, sharp blow.",
    "Burn peat after the logs give out.",
    "He ordered peach pie with ice cream.",
    "Weave the carpet on the right hand side.",
    "Hemp is a weed found in parts of the tropics.",
    "A lame back kept his score low.",
    "We find joy in the simplest things.",
    "Type out three lists of orders.",
    "The harder he tried the less he got done.",
    "The boss ran the show with a watchful eye.",
    "The cup cracked and spilled its contents.",
    "Paste can cleanse the most dirty brass.",
    "The slang word for raw whiskey is booze.",
    "It caught its hind paw in a rusty trap.",
    "The wharf could be seen at the farther shore.",
    "Feel the heat of the weak dying flame.",
    "The tiny girl took off her hat.",
    "A cramp is no small danger on a swim.",
    "He said the same phrase thirty times.",
    "Pluck the bright rose without leaves.",
    "Two plus seven is less than ten.",
    "The glow deepened in the eyes of the sweet girl.",
    "Bring your problems to the wise chief.",
    "Write a fond note to the friend you cherish.",
    "Clothes and lodging are free to new men.",
    "We frown when events take a bad turn.",
    "Port is a strong wine with a smoky taste.",
    "The young kid jumped the rusty gate.",
    "Guess the result from the first scores.",
    "A salt pickle tastes fine with ham.",
    "The just claim got the right verdict.",
    "Those thistles bend in a high wind.",
    "Pure bred poodles have curls.",
    "The tree top waved in a graceful way.",
    "The spot on the blotter was made by green ink.",
    "Mud was spattered on the front of his white shirt.",
    "The cigar burned a hole in the desk top.",
    "The empty flask stood on the tin tray.",
    "A speedy man can beat this track mark.",
    "He broke a new shoelace that day.",
    "The coffee stand is too high for the couch.",
    "The urge to write short stories is rare.",
    "The pencils have all been used.",
    "The pirates seized the crew of the lost ship.",
    "We tried to replace the coin but failed.",
    "She sewed the torn coat quite neatly.",
    "The sofa cushion is red and of light weight.",
    "The jacket hung on the back of the wide chair.",
    "At that high level the air is pure.",
    "Drop the two when you add the figures.",
    "A filing case is now hard to buy.",
    "An abrupt start does not win the prize.",
    "Wood is best for making toys and blocks.",
    "The office paint was a dull, sad tan.",
    "He knew the skill of the great young actress.",
    "A rag will soak up spilled water.",
    "A shower of dirt fell from the hot pipes.",
    "Steam hissed from the broken valve.",
    "The child almost hurt the small dog.",
    "There was a sound of dry leaves outside.",
    "The sky that morning was clear and bright blue.",
    "Torn scraps littered the stone floor.",
    "Sunday is the best part of the week.",
    "The doctor cured him with these pills.",
    "The new girl was fired today at noon.",
    "They felt gay when the ship arrived in port.",
    "Add the store's account to the last cent.",
    "Acid burns holes in wool cloth.",
    "Fairy tales should be fun to write.",
    "Eight miles of woodland burned to waste.",
    "The third act was dull and tired the players.",
    "A young child should not suffer fright.",
    "Add the column and put the sum here.",
    "We admire and love a good cook.",
    "There the flood mark is ten inches.",
    "He carved a head from the round block of marble.",
    "She has a smart way of wearing clothes.",
    "The fruit of a fig tree is apple shaped.",
    "Corn cobs can be used to kindle a fire.",
    "Where were they when the noise started.",
    "The paper box is full of thumb tacks.",
    "Sell your gift to a buyer at a good gain.",
    "The tongs lay beside the ice pail.",
    "The petals fall with the next puff of wind.",
    "Bring your best compass to the third class.",
    "They could laugh although they were sad.",
    "Farmers came in to thresh the oat crop.",
    "The brown house was on fire to the attic.",
    "The lure is used to catch trout and flounder.",
    "Float the soap on top of the bath water.",
    "A blue crane is a tall wading bird.",
    "A fresh start will work such wonders.",
    "The club rented the rink for the fifth night.",
    "After the dance, they went straight home.",
    "The hostess taught the new maid to serve.",
    "He wrote his last novel there at the inn.",
    "Even the worst will beat his low score.",
    "The cement had dried when he moved it.",
    "The loss of the second ship was hard to take.",
    "The fly made its way along the wall.",
    "Do that with a wooden stick.",
    "Live wires should be kept covered.",
    "The large house had hot water taps.",
    "It is hard to erase blue or red ink.",
    "Write at once or you may forget it.",
    "The doorknob was made of bright clean brass.",
    "The wreck occurred by the bank on Main Street.",
    "A pencil with black lead writes best.",
    "Coax a young calf to drink from a bucket.",
    "Schools for ladies teach charm and grace.",
    "The lamp shone with a steady green flame.",
    "They took the axe and the saw to the forest.",
    "The ancient coin was quite dull and worn.",
    "The shaky barn fell with a loud crash.",
    "Jazz and swing fans like fast music.",
    "Rake the rubbish up and then burn it.",
    "Slash the gold cloth into fine ribbons.",
    "Try to have the court decide the case.",
    "They are pushed back each time they attack.",
    "He broke his ties with groups of former friends.",
    "They floated on the raft to sun their white backs.",
    "The map had an X that meant nothing.",
    "Whitings are small fish caught in nets.",
    "Some ads serve to cheat buyers.",
    "Jerk the rope and the bell rings weakly.",
    "A waxed floor makes us lose balance.",
    "Madam, this is the best brand of corn.",
    "On the islands the sea breeze is soft and mild.",
    "The play began as soon as we sat down.",
    "This will lead the world to more sound and fury.",
    "Add salt before you fry the egg.",
    "The rush for funds reached its peak Tuesday.",
    "The birch looked stark white and lonesome.",
    "The box is held by a bright red snapper.",
    "To make pure ice, you freeze water.",
    "The first worm gets snapped early.",
    "Jump the fence and hurry up the bank.",
    "Yell and clap as the curtain slides back.",
    "They are men who walk the middle of the road.",
    "Both brothers wear the same size.",
    "In some form or other we need fun.",
    "The prince ordered his head chopped off.",
    "The houses are built of red clay bricks.",
    "Ducks fly north but lack a compass.",
    "Fruit flavors are used in fizz drinks.",
    "These pills do less good than others.",
    "Canned pears lack full flavor.",
    "The dark pot hung in the front closet.",
    "Carry the pail to the wall and spill it there.",
    "The train brought our hero to the big town.",
    "We are sure that one war is enough.",
    "Gray paint stretched for miles around.",
    "The rude laugh filled the empty room.",
    "High seats are best for football fans.",
    "Tea served from the brown jug is tasty.",
    "A dash of pepper spoils beef stew.",
    "A zestful food is the hot cross bun.",
    "The horse trotted around the field at a brisk pace.",
    "Find the twin who stole the pearl necklace.",
    "Cut the cord that binds the box tightly.",
    "The red tape bound the smuggled food.",
    "Look in the corner to find the tan shirt.",
    "The cold drizzle will halt the bond drive.",
    "Nine men were hired to dig the ruins.",
    "The junk yard had a mouldy smell.",
    "The flint sputtered and lit a pine torch.",
    "Soak the cloth and drown the sharp odor.",
    "The shelves were bare of both jam or crackers.",
    "A joy to every child is the swan boat.",
    "All sat frozen and watched the screen.",
    "A cloud of dust stung his tender eyes.",
    "To reach the end he needs much courage.",
    "Shape the clay gently into block form.",
    "A ridge on a smooth surface is a bump or flaw.",
    "Hedge apples may stain your hands green.",
    "Quench your thirst, then eat the crackers.",
    "Tight curls get limp on rainy days.",
    "The mute muffled the high tones of the horn.",
    "The gold ring fits only a pierced ear.",
    "The old pan was covered with hard fudge.",
    "Watch the log float in the wide river.",
    "The node on the stalk of wheat grew daily.",
    "The heap of fallen leaves was set on fire.",
    "Write fast if you want to finish early.",
    "His shirt was clean but one button was gone.",
    "The barrel of beer was a brew of malt and hops.",
    "Tin cans are absent from store shelves.",
    "Slide the box into that empty space.",
    "The plant grew large and green in the window.",
    "The beam dropped down on the workman's head.",
    "Pink clouds floated with the breeze.",
    "She danced like a swan, tall and graceful.",
    "The tube was blown and the tire flat and useless.",
    "It is late morning on the old wall clock.",
    "Let's all join as we sing the last chorus.",
    "The last switch cannot be turned off.",
    "The fight will end in just six minutes.",
    "The store walls were lined with colored frocks.",
    "The peace league met to discuss their plans.",
    "The rise to fame of a person takes luck.",
    "Paper is scarce, so write with much care.",
    "The quick fox jumped on the sleeping cat.",
    "The nozzle of the fire hose was bright brass.",
    "Screw the round cap on as tight as needed.",
    "Time brings us many changes.",
    "The purple tie was ten years old.",
    "Men think and plan and sometimes act.",
    "Fill the ink jar with sticky glue.",
    "He smoke a big pipe with strong contents.",
    "We need grain to keep our mules healthy.",
    "Pack the records in a neat thin case.",
    "The crunch of feet in the snow was the only sound.",
    "The copper bowl shone in the sun's rays.",
    "Boards will warp unless kept dry.",
    "The plush chair leaned against the wall.",
    "Glass will clink when struck by metal.",
    "Bathe and relax in the cool green grass.",
    "Nine rows of soldiers stood in a line.",
    "The beach is dry and shallow at low tide.",
    "The idea is to sew both edges straight.",
    "The kitten chased the dog down the street.",
    "Pages bound in cloth make a book.",
    "Try to trace the fine lines of the painting.",
    "Women form less than half of the group.",
    "The zones merge in the central part of town.",
    "A gem in the rough needs work to polish.",
    "Code is used when secrets are sent.",
    "Most of the news is easy for us to hear.",
    "He used the lathe to make brass objects.",
    "The vane on top of the pole revolved in the wind.",
    "Mince pie is a dish served to children.",
    "The clan gathered on each dull night.",
    "Let it burn, it gives us warmth and comfort.",
    "A castle built from sand fails to endure.",
    "A child's wit saved the day for us.",
    "Tack the strip of carpet to the worn floor.",
    "Next Tuesday we must vote.",
    "Pour the stew from the pot into the plate.",
    "Each penny shone like new.",
    "The man went to the woods to gather sticks.",
    "The dirt piles were lines along the road.",
    "The logs fell and tumbled into the clear stream.",
    "Just hoist it up and take it away.",
    "A ripe plum is fit for a king's palate.",
    "Our plans right now are hazy.",
    "Brass rings are sold by these natives.",
    "It takes a good trap to capture a bear.",
    "Feed the white mouse some flower seeds.",
    "The thaw came early and freed the stream.",
    "He took the lead and kept it the whole distance.",
    "The key you designed will fit the lock.",
    "Plead to the council to free the poor thief.",
    "Better hash is made of rare beef.",
    "This plank was made for walking on .",
    "The lake sparkled in the red hot sun.",
    "He crawled with care along the ledge.",
    "Tend the sheep while the dog wanders.",
    "It takes a lot of help to finish these.",
    "Mark the spot with a sign painted red.",
    "Take two shares as a fair profit.",
    "The fur of cats goes by many names.",
    "North winds bring colds and fevers.",
    "He asks no person to vouch for him.",
    "Go now and come here later.",
    "A sash of gold silk will trim her dress.",
    "Soap can wash most dirt away.",
    "That move means the game is over.",
    "He wrote down a long list of items.",
    "A siege will crack the strong defense.",
    "Grape juice and water mix well.",
    "Roads are paved with sticky tar.",
    "Fake stones shine but cost little.",
    "The drip of the rain made a pleasant sound.",
    "Smoke poured out of every crack.",
    "Serve the hot rum to the tired heroes.",
    "Much of the story makes good sense.",
    "The sun came up to light the eastern sky.",
    "Heave the line over the port side.",
    "A lathe cuts and trims any wood.",
    "It's a dense crowd in two distinct ways.",
    "His hip struck the knee of the next player.",
    "The stale smell of old beer lingers.",
    "The desk was firm on the shaky floor.",
    "It takes heat to bring out the odor.",
    "Beef is scarcer than some lamb.",
    "Raise the sail and steer the ship northward.",
    "A cone costs five cents on Mondays.",
    "A pod is what peas always grow in.",
    "Jerk that dart from the cork target.",
    "No cement will hold hard wood.",
    "We now have a new base for shipping.",
    "A list of names is carved around the base.",
    "The sheep were led home by a dog.",
    "Three for a dime, the young peddler cried.",
    "The sense of smell is better than that of touch.",
    "No hardship seemed to make him sad.",
    "Grace makes up for lack of beauty.",
    "Nudge gently but wake her now.",
    "The news struck doubt into restless minds.",
    "Once we stood beside the shore.",
    "A chink in the wall allowed a draft to blow.",
    "Fasten two pins on each side.",
    "A cold dip restores health and zest.",
    "He takes the oath of office each March.",
    "The sand drifts over the sills of the old house.",
    "The point of the steel pen was bent and twisted.",
    "There is a lag between thought and act.",
    "Seed is needed to plant the spring corn.",
    "Draw the chart with heavy black lines.",
    "The boy owed his pal thirty cents.",
    "The chap slipped into the crowd and was lost.",
    "Hats are worn to tea and not to dinner.",
    "The ramp led up to the wide highway.",
    "Beat the dust from the rug onto the lawn.",
    "Say it slowly but make it ring clear.",
    "The straw nest housed five robins.",
    "Screen the porch with woven straw mats.",
    "This horse will nose his way to the finish.",
    "The dry wax protects the deep scratch.",
    "He picked up the dice for a second roll.",
    "These coins will be needed to pay his debt.",
    "The nag pulled the frail cart along.",
    "Twist the valve and release hot steam.",
    "The vamp of the shoe had a gold buckle.",
    "The smell of burned rags itches my nose.",
    "New pants lack cuffs and pockets.",
    "The marsh will freeze when cold enough.",
    "They slice the sausage thin with a knife.",
    "The bloom of the rose lasts a few days.",
    "A gray mare walked before the colt.",
    "Breakfast buns are fine with a hot drink.",
    "Bottles hold four kinds of rum.",
    "The man wore a feather in his felt hat.",
    "He wheeled the bike past the winding road.",
    "Drop the ashes on the worn old rug.",
    "The desk and both chairs were painted tan.",
    "Throw out the used paper cup and plate.",
    "A clean neck means a neat collar.",
    "The couch cover and hall drapes were blue.",
    "The stems of the tall glasses cracked and broke.",
    "The wall phone rang loud and often.",
    "The clothes dried on a thin wooden rack.",
    "Turn out the lantern which gives us light.",
    "The cleat sank deeply into the soft turf.",
    "The bills were mailed promptly on the tenth of the month.",
    "To have is better than to wait and hope.",
    "The price is fair for a good antique clock.",
    "The music played on while they talked.",
    "Dispense with a vest on a day like this.",
    "The bunch of grapes was pressed into wine.",
    "He sent the figs, but kept the ripe cherries.",
    "The hinge on the door creaked with old age.",
    "The screen before the fire kept in the sparks.",
    "Fly by night and you waste little time.",
    "Thick glasses helped him read the print.",
    "Birth and death marks the limits of life.",
    "The chair looked strong but had no bottom.",
    "The kite flew wildly in the high wind.",
    "A fur muff is stylish once more.",
    "The tin box held priceless stones.",
    "We need an end of all such matter.",
    "The case was puzzling to the old and wise.",
    "The bright lanterns were gay on the dark lawn.",
    "We don't get much money but we have fun.",
    "The youth drove with zest, but little skill.",
    "Five years he lived with a shaggy dog.",
    "A fence cuts through the corner lot.",
    "The way to save money is not to spend much.",
    "Shut the hatch before the waves push it in.",
    "The odor of spring makes young hearts jump.",
    "Crack the walnut with your sharp side teeth.",
    "He offered proof in the form of a large chart.",
    "Send the stuff in a thick paper bag.",
    "A quart of milk is water for the most part.",
    "They told wild tales to frighten him.",
    "The three story house was built of stone.",
    "In the rear of the ground floor was a large passage.",
    "A man in a blue sweater sat at the desk.",
    "Oats are a food eaten by horse and man.",
    "Their eyelids droop for want of sleep.",
    "A sip of tea revives his tired friend.",
    "There are many ways to do these things.",
    "Tuck the sheet under the edge of the mat.",
    "A force equal to that would move the earth.",
    "We like to see clear weather.",
    "The work of the tailor is seen on each side.",
    "Take a chance and win a china doll.",
    "Shake the dust from your shoes, stranger.",
    "She was kind to sick old people.",
    "The square wooden crate was packed to be shipped.",
    "The dusty bench stood by the stone wall.",
    "We dress to suit the weather of most days.",
    "Smile when you say nasty words.",
    "A bowl of rice is free with chicken stew.",
    "The water in this well is a source of good health.",
    "Take shelter in this tent, but keep still.",
    "That guy is the writer of a few banned books.",
    "The little tales they tell are false.",
    "The door was barred, locked, and bolted as well.",
    "Ripe pears are fit for a queen's table.",
    "A big wet stain was on the round carpet.",
    "The kite dipped and swayed, but stayed aloft.",
    "The pleasant hours fly by much too soon.",
    "The room was crowded with a wild mob.",
    "This strong arm shall shield your honor.",
    "She blushed when he gave her a white orchid.",
    "The beetle droned in the hot June sun.",
    "Press the pedal with your left foot.",
    "Neat plans fail without luck.",
    "The black trunk fell from the landing.",
    "The bank pressed for payment of the debt.",
    "The theft of the pearl pin was kept secret.",
    "Shake hands with this friendly child.",
    "The vast space stretched into the far distance.",
    "A rich farm is rare in this sandy waste.",
    "His wide grin earned many friends.",
    "Flax makes a fine brand of paper.",
    "Hurdle the pit with the aid of a long pole.",
    "A strong bid may scare your partner stiff.",
    "Even a just cause needs power to win.",
    "Peep under the tent and see the clowns.",
    "The leaf drifts along with a slow spin.",
    "Cheap clothes are flashy but don't last.",
    "A thing of small note can cause despair.",
    "Flood the mails with requests for this book.",
    "A thick coat of black paint covered all.",
    "The pencil was cut to be sharp at both ends.",
    "Those last words were a strong statement.",
    "He wrote his name boldly at the top of the sheet.",
    "Dill pickles are sour but taste fine.",
    "Down that road is the way to the grain farmer.",
    "Either mud or dust are found at all times.",
    "The best method is to fix it in place with clips.",
    "If you mumble your speech will be lost.",
    "At night the alarm roused him from a deep sleep.",
    "Read just what the meter says.",
    "Fill your pack with bright trinkets for the poor.",
    "The small red neon lamp went out.",
    "Clams are small, round, soft, and tasty.",
    "The fan whirled its round blades softly.",
    "The line where the edges join was clean.",
    "Breathe deep and smell the piny air.",
    "It matters not if he reads these words or those.",
    "A brown leather bag hung from its strap.",
    "A toad and a frog are hard to tell apart.",
    "A white silk jacket goes with any shoes.",
    "A break in the dam almost caused a flood.",
    "Paint the sockets in the wall dull green.",
    "The child crawled into the dense grass.",
    "Bribes fail where honest men work.",
    "Trample the spark, else the flames will spread.",
    "The hilt of the sword was carved with fine designs.",
    "A round hole was drilled through the thin board.",
    "Footprints showed the path he took up the beach.",
    "She was waiting at my front lawn.",
    "A vent near the edge brought in fresh air.",
    "Prod the old mule with a crooked stick.",
    "It is a band of steel three inches wide.",
    "The pipe ran almost the length of the ditch.",
    "It was hidden from sight by a mass of leaves and shrubs.",
    "The weight of the package was seen on the high scale.",
    "Wake and rise, and step into the green outdoors.",
    "The green light in the brown box flickered.",
    "The brass tube circled the high wall.",
    "The lobes of her ears were pierced to hold rings.",
    "Hold the hammer near the end to drive the nail.",
    "Next Sunday is the twelfth of the month.",
    "Every word and phrase he speaks is true.",
    "He put his last cartridge into the gun and fired.",
    "They took their kids from the public school.",
    "Drive the screw straight into the wood.",
    "Keep the hatch tight and the watch constant.",
    "Sever the twine with a quick snip of the knife.",
    "Paper will dry out when wet.",
    "Slide the catch back and open the desk.",
    "Help the weak to preserve their strength.",
    "A sullen smile gets few friends.",
    "Stop whistling and watch the boys march.",
    "Jerk the cord, and out tumbles the gold.",
    "Slide the tray across the glass top.",
    "The cloud moved in a stately way and was gone.",
    "Light maple makes for a swell room.",
    "Set the piece here and say nothing.",
    "Dull stories make her laugh.",
    "A stiff cord will do to fasten your shoe.",
    "Get the trust fund to the bank early.",
    "Choose between the high road and the low.",
    "A plea for funds seems to come again.",
    "He lent his coat to the tall gaunt stranger.",
    "There is a strong chance it will happen once more.",
    "The duke left the park in a silver coach.",
    "Greet the new guests and leave quickly.",
    "When the frost has come it is time for turkey.",
    "Sweet words work better than fierce.",
    "A thin stripe runs down the middle.",
    "A six comes up more often than a ten.",
    "Lush ferns grow on the lofty rocks.",
    "The ram scared the school children off.",
    "The team with the best timing looks good.",
    "The farmer swapped his horse for a brown ox.",
    "Sit on the perch and tell the others what to do.",
    "A steep trail is painful for our feet.",
    "The early phase of life moves fast.",
    "Green moss grows on the northern side.",
    "Tea in thin china has a sweet taste.",
    "Pitch the straw through the door of the stable.",
    "The latch on the back gate needed a nail.",
    "The goose was brought straight from the old market.",
    "The sink is the thing in which we pile dishes.",
    "A whiff of it will cure the most stubborn cold.",
    "The facts don't always show who is right.",
    "She flaps her cape as she parades the street.",
    "The loss of the cruiser was a blow to the fleet.",
    "Loop the braid to the left and then over.",
    "Plead with the lawyer to drop the lost cause.",
    "Calves thrive on tender spring grass.",
    "Post no bills on this office wall.",
    "Tear a thin sheet from the yellow pad.",
    "A cruise in warm waters in a sleek yacht is fun.",
    "A streak of color ran down the left edge.",
    "It was done before the boy could see it.",
    "Crouch before you jump or miss the mark.",
    "Pack the kits and don't forget the salt.",
    "The square peg will settle in the round hole.",
    "Fine soap saves tender skin.",
    "Poached eggs and tea must suffice.",
    "Bad nerves are jangled by a door slam.",
    "Ship maps are different from those for planes.",
    "Dimes showered down from all sides.",
    "They sang the same tunes at each party.",
    "The sky in the west is tinged with orange red.",
    "The pods of peas ferment in bare fields.",
    "The horse balked and threw the tall rider.",
    "The hitch between the horse and cart broke.",
    "Pile the coal high in the shed corner.",
    "A gold vase is both rare and costly.",
    "The knife was hung inside its bright sheath.",
    "The rarest spice comes from the far East.",
    "The roof should be tilted at a sharp slant.",
    "A smatter of French is worse than none.",
    "The mule trod the treadmill day and night.",
    "The aim of the contest is to raise a great fund.",
    "To send it now in large amounts is bad.",
    "There is a fine hard tang in salty air.",
    "Cod is the main business of the north shore.",
    "The slab was hewn from heavy blocks of slate.",
    "Dunk the stale biscuits into strong drink.",
    "Hang tinsel from both branches.",
    "Cap the jar with a tight brass cover.",
    "The poor boy missed the boat again.",
    "Be sure to set that lamp firmly in the hole.",
    "Pick a card and slip it under the pack.",
    "A round mat will cover the dull spot.",
    "The first part of the plan needs changing.",
    "A good book informs of what we ought to know.",
    "The mail comes in three batches per day.",
    "You cannot brew tea in a cold pot.",
    "Dots of light betrayed the black cat.",
    "Put the chart on the mantel and tack it down.",
    "The night shift men rate extra pay.",
    "The red paper brightened the dim stage.",
    "See the player scoot to third base.",
    "Slide the bill between the two leaves.",
    "Many hands help get the job done.",
    "We don't like to admit our small faults.",
    "No doubt about the way the wind blows.",
    "Dig deep in the earth for pirate's gold.",
    "The steady drip is worse than a drenching rain.",
    "A flat pack takes less luggage space.",
    "Green ice frosted the punch bowl.",
    "A stuffed chair slipped from the moving van.",
    "The stitch will serve but needs to be shortened.",
    "A thin book fits in the side pocket.",
    "The gloss on top made it unfit to read.",
    "The hail pattered on the burnt brown grass.",
    "Seven seals were stamped on great sheets.",
    "Our troops are set to strike heavy blows.",
    "The store was jammed before the sale could start.",
    "It was a bad error on the part of the new judge.",
    "One step more and the board will collapse.",
    "Take the match and strike it against your shoe.",
    "The pot boiled but the contents failed to jell.",
    "The baby puts his right foot in his mouth.",
    "The bombs left most of the town in ruins.",
    "Stop and stare at the hard working man.",
    "The streets are narrow and full of sharp turns.",
    "The pup jerked the leash as he saw a feline shape.",
    "Open your book to the first page.",
    "Fish evade the net and swim off.",
    "Dip the pail once and let it settle.",
    "Will you please answer that phone.",
    "The big red apple fell to the ground.",
    "The curtain rose and the show was on.",
    "The young prince became heir to the throne.",
    "He sent the boy on a short errand.",
    "Leave now and you will arrive on time.",
    "The corner store was robbed last night.",
    "A gold ring will please most any girl.",
    "The long journey home took a year.",
    "She saw a cat in the neighbor's house.",
    "A pink shell was found on the sandy beach.",
    "Small children came to see him.",
    "The grass and bushes were wet with dew.",
    "The blind man counted his old coins.",
    "A severe storm tore down the barn.",
    "She called his name many times.",
    "When you hear the bell, come quickly."
]


lj_valid = [
    "The overwhelming majority of people in this country know how to sift the wheat from the chaff in what they hear and what they read.",
    "If somebody did that to me, a lousy trick like that, to take my wife away, and all the furniture, I would be mad as hell, too.",
    "as is shown by the report of the Commissioners to inquire into the state of the municipal corporations in 1835.",
    "Even the Caslon type when enlarged shows great shortcomings in this respect:",
    "All the committee could do in this respect was to throw the responsibility on others.",
    "These pungent and well grounded strictures applied with still greater force to the unconvicted prisoner, the man who came to the prison innocent, and still uncontaminated.",
    "and recognized as one of the frequenters of the bogus law stationers. His arrest led to that of others.",
    "Oswald was, however, willing to discuss his contacts with Soviet authorities. He denied having any involvement with Soviet intelligence agencies",
    "The first physician to see the President at Parkland Hospital was Dr. Charles J. Carrico, a resident in general surgery.",
    "during the morning of November 22 prior to the motorcade.",
    "On occasion the Secret Service has been permitted to have an agent riding in the passenger compartment with the President.",
    "although at Mr. Buxton's visit a new jail was in process of erection, the first step towards reform since Howard's visitation in 1774.",
    "or theirs might be one of many, and it might be considered necessary to make an example.",
    "The Warren Commission Report. By The President's Commission on the Assassination of President Kennedy. Chapter 7. Lee Harvey Oswald.",
    "Mr. Wakefield winds up his graphic but somewhat sensational account by describing another religious service, which may appropriately be inserted here.",
    "A modern artist would have difficulty in doing such accurate work.",
    "with the particular purposes of the agency involved. The Commission recognizes that this is a controversial area",
    "Oswald's Marine training in marksmanship, his other rifle experience and his established familiarity with this particular weapon",
    "According to O'Donnell, quote, we had a motorcade wherever we went, end quote.",
    "Dr. Clark, who most closely observed the head wound.",
    "Euins, who was on the southwest corner of Elm and Houston Streets testified that he could not describe the man he saw in the window.",
    "Energy enters the plant, to a small extent.",
    "once you know that you must put the cross hairs on the target and that is all that is necessary.",
    "the fatal consequences whereof might be prevented if the justices of the peace were duly authorized",
    "Speaking on a debate on prison matters, he declared that",
    "he was reported to have fallen away to a shadow.",
    "His disappearance gave color and substance to evil reports already in circulation that the will and conveyance above referred to",
    "Here the tread wheel was in use, there cellular cranks, or hard labor machines.",
    "you tap gently with your heel upon the shoulder of the dromedary to urge her on.",
    "This plan of mine is no attack on the Court;",
    "No nightclubs or bowling alleys, no places of recreation except the trade union dances. I have had enough.",
    "The police asked him whether he could pick out his passenger from the lineup.",
    "During his Presidency, Franklin D. Roosevelt made almost four hundred journeys and traveled more than three hundred fifty thousand miles.",
    "He was seen afterwards smoking and talking with his hosts in their back parlor, and never seen again alive.",
    "long narrow rooms, one 36 feet, six 23 feet, and the eighth 18.",
    "We come to the sermon.",
    "even when the high sheriff had told him there was no possibility of a reprieve, and within a few hours of execution.",
    "but there is a system for the immediate notification of the Secret Service by the confining institution when a subject is released or escapes.",
    "When other pleasures palled he took a theater, and posed as a munificent patron of the dramatic art.",
    "(old exchange rate) in addition to his factory salary of approximately equal amount",
    "Hill had both feet on the car and was climbing aboard to assist President and Mrs. Kennedy.",
    "seeing that since the establishment of the Central Criminal Court, Newgate received prisoners for trial from several counties.",
    "then let twenty days pass, and at the end of that time station near the Chaldasan gates a body of four thousand.",
    "While they were in a state of insensibility the murder was committed.",
    "reached the same conclusion as Latona that the prints found on the cartons were those of Lee Harvey Oswald.",
    "These were damnatory facts which well supported the prosecution.",
    "but were the precautions too minute, the vigilance too close to be eluded or overcome?",
    "but his scribe wrote it in the manner customary for the scribes of those days to write of their royal masters.",
    "The inadequacy of the jail was noticed and reported upon again and again by the grand juries of the city of London.",
    "At last, in the twentieth month.",
    "which he kept concealed in a hiding place with a trap door just under his bed.",
    "He married a lady also belonging to the Society of Friends, who brought him a large fortune, which, and his own money, he put into a city firm.",
    "Roger D. Craig, a deputy sheriff of Dallas County.",
    "Other officials, great lawyers, governors of prisons, and chaplains supported this view.",
    "who came from his room ready dressed, a suspicious circumstance, as he was always late in the morning.",
    "is closely reproduced in the life history of existing deer. Or, in other words.",
    "accordingly they committed to him the command of their whole army, and put the keys of their city into his hands.",
    "Mrs. Kennedy chose the hospital in Bethesda for the autopsy because the President had served in the Navy.",
    "From those willing to join in establishing this hoped for period of peace.",
    "Müller, Müller, He's the man, till a diversion was created by the appearance of the gallows, which was received with continuous yells.",
    "Years later, when the archaeologists could readily distinguish the false from the true.",
    "his defense being that he had intended to commit suicide, but that, on the appearance of this officer who had wronged him.",
    "together with a great increase in the payrolls, there has come a substantial rise in the total of industrial profits",
    "After this the sheriffs sent for another rope, but the spectators interfered, and the man was carried back to jail.",
    "and improve the morals of the prisoners, and shall insure the proper measure of punishment to convicted offenders.",
    "drove to the northwest corner of Elm and Houston, and parked approximately 10 feet from the traffic signal.",
    "This is the approximate time he entered the rooming house, according to Earlene Roberts, the housekeeper there.",
    "The criteria in effect prior to November 22, 1963, for determining whether to accept material for the PRS general files",
    "and the deepest anxiety was felt that the crime, if crime there had been, should be brought home to its perpetrator.",
    "but his sporting operations did not prosper, and he became a needy man, always driven to desperate straits for cash.",
    "He was soon afterwards arrested on suspicion, and a search of his lodgings brought to light several garments saturated with blood;",
    "He never reached the cistern, but fell back into the yard, injuring his legs severely.",
    "when he was finally apprehended in the Texas Theatre. Although it is not fully corroborated by others who were present.",
    "and she must have run down the stairs ahead of Oswald and would probably have seen or heard him.",
    "afterwards express a wish to murder the Recorder for having kept them so long in suspense.",
    "nearly indefinitely deferred.",
    "On October 25.",
    "They entered a stone cold room, and were presently joined by the prisoner.",
    "that he could only testify with certainty that the print was less than three days old.",
    "Mrs. Mary Brock, the wife of a mechanic who worked at the station, was there at the time and she saw a white male.",
    "Chapter 7. Lee Harvey Oswald Background and Possible Motives, Part 1.",
    "The arguments he used to justify his use of the alias suggest that Oswald may have come to think that the whole world was becoming involved",
    "the number and names on watches, were carefully removed or obliterated after the goods passed out of his hands.",
    "On the 7th July, 1837.",
    "contracted with sheriffs and conveners to work by the job.",
    "at a distance from the prison.",
    "These principles of homology are essential to a correct interpretation of the facts of morphology.",
    "On one occasion Mrs. Johnson, accompanied by two Secret Service agents, left the room to see Mrs. Kennedy and Mrs. Connally.",
    "which Sir Joshua Jebb told the committee he considered the proper elements of penal discipline.",
    "At the first the boxes were impounded, opened, and found to contain many of O'Connor's effects.",
    "on Brennan's subsequent certain identification of Lee Harvey Oswald as the man he saw fire the rifle.",
    "11. If I am alive and taken prisoner.",
    "yet he could not overcome the strange fascination it had for him, and remained by the side of the corpse till the stretcher came.",
    'I noticed when I went out that the light was on".',
    "He was never satisfied with anything.",
    "and others who were present say that no agent was inebriated or acted improperly.",
    'He was in consequence put out of the protection of their internal law ". Their code was a subject of some curiosity.',
    "Let me retrace my steps, and speak more in detail of the treatment of the condemned in those bloodthirsty and brutally indifferent days.",
    "The original plan called for the President to spend only one day in the State, making whirlwind visits to Dallas, Fort Worth, San Antonio, and Houston.",
    "Mr. Sturges Bourne, Sir James Mackintosh, Sir James Scarlett, and William Wilberforce.",
]




our_LJ_dict = {
	'LJ034-0035.wav' : "The position of this palmprint on the carton was parallel with the long axis of the box and at right angles with the short axis.",
	'LJ023-0033.wav' : "We will not allow ourselves to run around in new circles of futile discussion and debate, always postponing the day of decision.",
	'LJ003-0319.wav' : "Provided only that their security was not jeopardized, and dependent upon the enforcement of another new rule.",
	'LJ016-0277.wav' : "This is proved by contemporary accounts, especially one graphic and realistic article which appeared in the 'Times'.",
	'LJ050-0022.wav' : "A formal and thorough description of the responsibilities of the advance agent is now in preparation by the Service.",
	'LJ002-0225.wav' : "The rentals of rooms and fees went to the warden, whose income was two thousand three hundred seventy two pounds.",
	'LJ048-0252.wav' : "Three of these agents occupied positions on the running boards of the car, and the fourth was seated in the car.",
	'LJ024-0054.wav' : "Democracy will have failed far beyond the importance to it of any king of precedent concerning the judiciary.",
	'LJ028-0421.wav' : "it was the beginning of the great collections of Babylonian antiquities in the museums of the Western world.",
	'LJ015-0025.wav' : "The bank enjoyed an excellent reputation, it had a good connection, and was supposed to be perfectly sound.",
	'LJ016-0054.wav' : "But he did not like the risk of entering a room by the fireplace, and the chances of detection it offered.",
	'LJ006-0021.wav' : "Later on, he had devoted himself to the personal investigation of the prisons of the United States.",
	'LJ016-0274.wav' : "And the windows of the opposite houses, which commanded a good view, as usual fetched high prices.",
	'LJ002-0171.wav' : "The boy declared he saw no one, and accordingly passed through without paying the toll of a penny.",
	'LJ021-0139.wav' : "There should be at least a full and fair trial given to these means of ending industrial warfare.",
	'LJ003-0282.wav' : "Many years were to elapse before these objections should be fairly met and universally overcome.",
	'LJ048-0288.wav' : "Might have been more alert in the Dallas motorcade if they had retired promptly in Fort Worth.",
	'LJ021-0025.wav' : "And in many directions, the intervention of that organized control which we call government",
	'LJ021-0140.wav' : "and in such an effort we should be able to secure for employers and employees and consumers.",
	'LJ010-0027.wav' : "Nor did the methods by which they were perpetrated greatly vary from those in times past.",
	'LJ029-0004.wav' : "The narrative of these events is based largely on the recollections of the participants.",
	'LJ046-0191.wav' : "It had established periodic regular review of the status of four hundred individuals.",
	'LJ030-0063.wav' : "He had repeated this wish only a few days before, during his visit to Tampa, Florida.",
	'LJ018-0349.wav' : "His disclaimer, distinct and detailed on every point, was intended simply for effect.",
	'LJ033-0072.wav' : "I then stepped off of it and the officer picked it up in the middle and it bent so.",
	'LJ008-0085.wav' : "The fire had not quite burnt out at twelve, in nearly four hours, that is to say.",
	'LJ021-0040.wav' : "The second step we have taken in the restoration of normal business enterprise.",
	'LJ027-0006.wav' : "In all these lines the facts are drawn together by a strong thread of unity.",
	'LJ002-0260.wav' : "Yet the public opinion of the whole body seems to have checked dissipation.",
	'LJ013-0055.wav' : "The jury did not believe him, and the verdict was for the defendants.",
	'LJ008-0215.wav' : "One by one the huge uprights of black timber were fitted together.",
	'LJ018-0206.wav' : "He was a tall, slender man, with a long face and iron gray hair.",
	'LJ004-0239.wav' : "He had been committed for an offense for which he was acquitted.",
	'LJ037-0007.wav' : "Three others subsequently identified Oswald from a photograph.",
	'LJ037-0248.wav' : "The eyewitnesses vary in their identification of the jacket.",
	'LJ019-0055.wav' : "High authorities were in favor of continuous separation.",
	'LJ038-0035.wav' : "Oswald rose from his seat, bringing up both hands.",
	'LJ010-0297.wav' : "But there were other notorious cases of forgery.",
	'LJ019-0371.wav' : "Yet the law was seldom if ever enforced.",
	'LJ018-0159.wav' : "This was all the police wanted to know."
}

our_LJ_set = list(our_LJ_dict.values())


Attention_checks  = {
    'LJ012-0049.wav' :	"led him to think seriously of trying his fortunes in another land.",
    'LJ048-0200.wav' : "paying particular attention to the crowd for any unusual activity."
}
